### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by SeanMcP** [SeanMcP/sushi-go-friend#10]
Something broke after switching from yarn to npm, maybe 992a582aadc7e0cc37769b6926fd3a15fb6fd537 or 959e619aadc5df0a66df156fc63dde5a53f1cd4b?

<details>
<summary>Error log</summary>
```
2:44:22 PM: Build ready to start
2:44:24 PM: build-image version: 3bcb38c35508b42e9121d4badfe6d8c66fd7a3f0
2:44:24 PM: build-image tag: v4.3.2
2:44:24 PM: buildbot version: 5cab5d8c0024e963b88f65476ed3b17d45dd7222
2:44:24 PM: Fetching cached dependencies
2:44:24 PM: Failed to fetch cache, continuing with build
2:44:24 PM: Starting to prepare the repo for build
2:44:24 PM: No cached dependencies found. Cloning fresh repo
2:44:24 PM: git clone https://github.com/SeanMcP/sushi-go-friend
2:44:25 PM: Preparing Git Reference refs/heads/master
2:44:25 PM: Parsing package.json dependencies
2:44:26 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'build' versus 'build/' in the Netlify UI
2:44:26 PM: Starting build script
2:44:26 PM: Installing dependencies
2:44:26 PM: Python version set to 2.7
2:44:27 PM: Downloading and installing node v8.17.0...
2:44:27 PM: Downloading https://nodejs.org/dist/v8.17.0/node-v8.17.0-linux-x64.tar.xz...
2:44:27 PM: Computing checksum with sha256sum
2:44:27 PM: Checksums matched!
2:44:29 PM: Now using node v8.17.0 (npm v6.13.4)
2:44:29 PM: Started restoring cached build plugins
2:44:29 PM: Finished restoring cached build plugins
2:44:29 PM: Attempting ruby version 2.7.2, read from environment
2:44:30 PM: Using ruby version 2.7.2
2:44:31 PM: Using PHP version 8.0
2:44:31 PM: Started restoring cached node modules
2:44:31 PM: Finished restoring cached node modules
2:44:31 PM: Installing NPM modules using NPM version 6.13.4
2:45:10 PM: > husky@1.3.1 install /opt/build/repo/node_modules/husky
2:45:10 PM: > node husky install
2:45:10 PM: husky > setting up git hooks
2:45:10 PM: CI detected, skipping Git hooks installation.
2:45:11 PM: > core-js@2.6.12 postinstall /opt/build/repo/node_modules/babel-runtime/node_modules/core-js
2:45:11 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:45:11 PM: > core-js@3.17.3 postinstall /opt/build/repo/node_modules/core-js
2:45:11 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:45:11 PM: > core-js-pure@3.17.3 postinstall /opt/build/repo/node_modules/core-js-pure
2:45:11 PM: > node -e "try{require('./postinstall')}catch(e){}"
2:45:11 PM: > ejs@2.7.4 postinstall /opt/build/repo/node_modules/ejs
2:45:11 PM: > node ./postinstall.js
2:45:14 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
2:45:14 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:45:14 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
2:45:14 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:45:14 PM: npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
2:45:14 PM: npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
2:45:14 PM: added 2151 packages from 734 contributors and audited 2157 packages in 42.828s
2:45:17 PM: 151 packages are looking for funding
2:45:17 PM:   run `npm fund` for details
2:45:17 PM: found 27 vulnerabilities (8 moderate, 18 high, 1 critical)
2:45:17 PM:   run `npm audit fix` to fix them, or `npm audit` for details
2:45:17 PM: NPM modules installed
2:45:18 PM: Started restoring cached go cache
2:45:18 PM: Finished restoring cached go cache
2:45:18 PM: Installing Go version 1.10
2:45:23 PM: unset GOOS;
2:45:23 PM: unset GOARCH;
2:45:23 PM: export GOROOT='/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64';
2:45:23 PM: export PATH="/opt/buildhome/.gimme_cache/versions/go1.10.linux.amd64/bin:${PATH}";
2:45:23 PM: go version >&2;
2:45:23 PM: export GIMME_ENV="/opt/buildhome/.gimme_cache/env/go1.10.linux.amd64.env"
2:45:23 PM: go version go1.10 linux/amd64
2:45:23 PM: Installing missing commands
2:45:23 PM: Verify run directory
2:45:24 PM: ​
2:45:24 PM: ────────────────────────────────────────────────────────────────
2:45:24 PM:   Netlify Build                                                 
2:45:24 PM: ────────────────────────────────────────────────────────────────
2:45:24 PM: ​
2:45:24 PM: ❯ Version
2:45:24 PM:   @netlify/build 18.13.12
2:45:24 PM: ​
2:45:24 PM: ❯ Flags
2:45:24 PM:   baseRelDir: false
2:45:24 PM:   buildId: 6164860658902700d466ae19
2:45:24 PM:   deployId: 6164860658902700d466ae1b
2:45:24 PM: ​
2:45:24 PM: ❯ Current directory
2:45:24 PM:   /opt/build/repo
2:45:24 PM: ​
2:45:24 PM: ❯ Config file
2:45:24 PM:   No config file was defined: using default values.
2:45:24 PM: ​
2:45:24 PM: ❯ Context
2:45:24 PM:   production
2:45:24 PM: ​
2:45:24 PM: ────────────────────────────────────────────────────────────────
2:45:24 PM:   1. Build command from Netlify app                             
2:45:24 PM: ────────────────────────────────────────────────────────────────
2:45:24 PM: ​
2:45:24 PM: $ npm run build
2:45:24 PM: > sushi-go-friend@0.1.1 build /opt/build/repo
2:45:24 PM: > react-scripts build
2:45:25 PM: /opt/build/repo/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
2:45:25 PM:       } catch {
2:45:25 PM:               ^
2:45:25 PM: SyntaxError: Unexpected token {
2:45:25 PM:     at createScript (vm.js:80:10)
2:45:25 PM:     at Object.runInThisContext (vm.js:139:10)
2:45:25 PM:     at Module._compile (module.js:617:28)
2:45:25 PM:     at Object.Module._extensions..js (module.js:664:10)
2:45:25 PM:     at Module.load (module.js:566:32)
2:45:25 PM:     at tryModuleLoad (module.js:506:12)
2:45:25 PM:     at Function.Module._load (module.js:498:3)
2:45:25 PM:     at Module.require (module.js:597:17)
2:45:25 PM:     at require (internal/module.js:11:18)
2:45:25 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
2:45:25 PM: npm ERR! code ELIFECYCLE
2:45:25 PM: npm ERR! errno 1
2:45:25 PM: npm ERR! sushi-go-friend@0.1.1 build: `react-scripts build`
2:45:25 PM: npm ERR! Exit status 1
2:45:25 PM: npm ERR!
2:45:25 PM: npm ERR! Failed at the sushi-go-friend@0.1.1 build script.
2:45:25 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2:45:25 PM: npm ERR! A complete log of this run can be found in:
2:45:25 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-10-11T18_45_25_219Z-debug.log
2:45:25 PM: ​
2:45:25 PM: ────────────────────────────────────────────────────────────────
2:45:25 PM:   "build.command" failed                                        
2:45:25 PM: ────────────────────────────────────────────────────────────────
2:45:25 PM: ​
2:45:25 PM:   Error message
2:45:25 PM:   Command failed with exit code 1: npm run build
2:45:25 PM: ​
2:45:25 PM:   Error location
2:45:25 PM:   In Build command from Netlify app:
2:45:25 PM:   npm run build
2:45:25 PM: ​
2:45:25 PM:   Resolved config
2:45:25 PM:   build:
2:45:25 PM:     command: npm run build
2:45:25 PM:     commandOrigin: ui
2:45:25 PM:     publish: /opt/build/repo/build
2:45:25 PM:     publishOrigin: ui
2:45:25 PM: Caching artifacts
2:45:25 PM: Started saving node modules
2:45:25 PM: Finished saving node modules
2:45:25 PM: Started saving build plugins
2:45:25 PM: Finished saving build plugins
2:45:25 PM: Started saving pip cache
2:45:25 PM: Finished saving pip cache
2:45:25 PM: Started saving emacs cask dependencies
2:45:25 PM: Finished saving emacs cask dependencies
2:45:25 PM: Started saving maven dependencies
2:45:25 PM: Finished saving maven dependencies
2:45:25 PM: Started saving boot dependencies
2:45:25 PM: Finished saving boot dependencies
2:45:25 PM: Started saving rust rustup cache
2:45:25 PM: Finished saving rust rustup cache
2:45:25 PM: Started saving go dependencies
2:45:27 PM: Finished saving go dependencies
2:45:29 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
2:45:29 PM: Creating deploy upload records
2:45:29 PM: Failing build: Failed to build site
2:45:29 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
2:45:29 PM: Finished processing build request in 1m5.250060686s
```
</details>

This should be reproduceable locally, so figure that out when you get a chance.

**Comment by SeanMcP** [comment]
Fixed by setting the `NODE_VERSION` environment variable in Netlify.
